### ISSUE TITLE
[ISSUE]: It doesn't play anything except the included XRick

### ISSUE THREAD

**Issue by NathanNeurotic** [koraxial/Xbox-2-PlayStation-Emulator-AlFa#1]
### Checks

- [X] I have checked existing [__OPL issues__](https://github.com/ps2homebrew/Open-PS2-Loader/issues) for duplicates and found none
- [X] I am using either OPL [latest stable version](https://github.com/ps2homebrew/Open-PS2-Loader/releases/latest), or [archived version](https://mega.nz/folder/Ndwi1bAK#oLWNhH_g-h0p4BoT4c556A) or [__OPL beta version__](https://github.com/ps2homebrew/open-ps2-loader/releases)

### Describe the issue

I can't play any Xbox games, even if I somehow manage to get them to show up in the first place.

### Console model

SCPH-79000

### OPL version / revision

X2P

### In which device(s) have you experienced this issue?

USB

### Context and extra information

Why no work?

**Comment by NathanNeurotic** [comment]
Oh, its an April Fools Joke! Got 'em!

**Comment by koraxial** [comment]
![image](https://github.com/koraxial/Xbox-2-PlayStation-Emulator-AlFa/assets/151830691/41229c85-ddfa-484f-9004-eb5ef924d4c5)
